baseURL = "https://studentathlet.es"
languageCode = "en-us"
title = "Student Athletes"
themesDir = "./themes/"
theme = "hugo-serif-theme"
publishDir = "docs"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_call_box = true

  [params.logo]
    mobile = "/images/favicon.svg"
    mobile_height = "36px"
    desktop = "/images/logo/Student_Athletes_Logo.svg"
    desktop_height = "36px"
    alt = "Student Athletes - Advocating for Unionization"

  [params.homepage_meta_tags]
    meta_description = "College Athletics is Big Business. It's time they pay recognize and pay their labor."
    meta_og_title = "Student Athletes"
    meta_og_type = "website"
    meta_og_url = "https://studentathlet.es"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
    meta_og_description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
    meta_twitter_card = "summary"
    meta_twitter_site = "@twitter"
    meta_twitter_creator = "@bbthorson"

  [params.footer]
    copyright_text = 'Free Hugo theme by <a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>'

[menu]
  # Main Menu
  [[menu.main]]
    name = "Vision"
    url = "/vision/"
      weight = 1

  [[menu.main]]
      name = "Team"
      url = "/team/"
      weight = 2

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
      weight = 2
